export const homepage = {
  eyebrow: "HGV and transport training",
  title: "HGV training at Bristol, Taunton and Exeter",
  lede: "Practical Category C and Category C+E licence training, with Driver CPC, ADR and Operator CPC courses for working drivers and transport managers.",
  exampleNote:
    "Demonstration website: Webco Professional is a fictional training provider, and the locations and contact details shown are samples.",
  routesTitle: "What do you want to drive or achieve?",
  routesIntro: "Pick the route closest to what you need.",
  coreTitle: "Core HGV training",
  coreIntro: "Our three main routes. If you are choosing between licences, the overview compares them side by side.",
  furtherTitle: "Further training",
  furtherIntro: "ADR for drivers who carry dangerous goods by road, and Operator CPC for people who manage transport operations.",
  whyTitle: "Why train here",
  whyIntro: "How we run our courses, from your first enquiry to the next step.",
  howTitle: "How training works",
  howIntro: "Four steps from first enquiry to the next stage. We confirm the length of your course when you enquire.",
  locationsTitle: "Training locations",
  locationsIntro: "Three training bases in the South West. Each base page lists the courses that run there.",
  proofTitle: "Learner feedback",
  proofIntro: "What learners say about training at our bases.",
  operationsTitle: "Instructors, vehicles and facilities",
  operationsIntro: "The teams who deliver our courses, and the vehicles and facilities our bases use.",
  guidesTitle: "Guides",
  guidesIntro: "Plain explanations of the licence, the medical and the test, with links to the relevant course pages.",
  faqTitle: "Questions",
  ctaTitle: "Ask about a course",
  ctaLede: "Tell us which course you want, which base you prefer, and how you would like to be contacted.",
} as const;
