export const homepage = {
  eyebrow: "HGV and transport training",
  title: "HGV training at Bristol, Taunton and Exeter",
  lede: "Category C, Category C+E and Driver CPC, plus ADR and Operator CPC. Each course and each base has its own page.",
  exampleNote:
    "Bristol, Taunton, Exeter and the phone number are examples. This is a demonstration website, not a training business.",
  routesTitle: "What do you want to drive or achieve?",
  routesIntro: "Choose a route. Each choice opens the page that explains it.",
  coreTitle: "Core HGV training",
  coreIntro: "The three main routes. The overview compares them if you are choosing between licences.",
  furtherTitle: "Further training",
  furtherIntro: "ADR and Operator CPC, for drivers and transport managers who need more than the vehicle entitlement.",
  whyTitle: "Why train here",
  whyIntro: "What this provider site sets out. No pass rate, award or review score is shown.",
  howTitle: "How training works",
  howIntro: "Four steps. Course length is confirmed when you enquire.",
  locationsTitle: "Training locations",
  locationsIntro:
    "Three example bases. Each page lists only the courses offered there. Nearby towns do not have their own pages.",
  proofTitle: "Learner feedback",
  proofIntro: "Example wording for the layout. These are not real reviews, and no score is shown.",
  operationsTitle: "Instructors, vehicles and facilities",
  operationsIntro:
    "Example profiles and example facilities. No instructor is named, and no vehicle make or yard is claimed.",
  guidesTitle: "Guides",
  guidesIntro: "Plain explanations of the licence, the medical and the test, with links to the relevant course pages.",
  faqTitle: "Questions",
  ctaTitle: "Ask about a course",
  ctaLede: "Say which course you want, which example base you prefer, and how you would like to be contacted.",
} as const;
